version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    environment:
      - MONGODB_URI
    ports: 
      - 80:5000
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:4.4.3-bionic
    ports: 
      - 27017:27017
    restart: always